unify bash,zsh,ksh,sh initialization

diff --git a/dot_config/bash/interactive b/dot_config/bash/interactive
--- a/dot_config/bash/interactive
+++ b/dot_config/bash/interactive
@@ -1,3 +1,42 @@
 . ~/.config/shell/interactive
 
+bash_data_dir="$XDG_DATA_HOME/bash"
+[ ! -d "$bash_data_dir" ] && mkdir -p "$bash_data_dir"
+
 alias d="dirs -v"
+
+
+### History
+# We export these variables here in case of starting terminal in another shell and then starting bash, we need to overwrite history config
+export HISTSIZE=100000
+export HISTFILE="$bash_data_dir/bash_history"
+
+### Keybindings
+#bind '"jk":vi-movement-mode'
+#bind "\C-p":history-search-backward
+#bind "\C-n":history-search-forward
+
+
+### Prompt
+# Depth of `$PWD` is decided by this.
+export PROMPT_DIRTRIM=2
+
+# `exit_code' Should be first command in `PROMPT_COMMAND' to be
+# executed or else return status will always be 0/true (If functions in
+# `PROMPT_COMMAND' are written proper :)
+[ -n "$PROMPT_COMMAND" ] && PROMPT_COMMAND="exit_code;$PROMPT_COMMAND" ||
+    PROMPT_COMMAND="exit_code"
+
+exit_code() {
+    EXIT="$?"
+
+    # PS1 needs to be reset or else it will be appended every time to
+    # previous one.
+    PS1=""
+
+    [ "$EXIT" = "0" ] && EXITCOL=$bldwht || EXITCOL=$bldred
+
+    # This will be final prompt, whatever set earlier will be
+    # overwritten by this.
+    export PS1="\[\$EXITCOL\]\w\[\033[01;38;5;208m\]\$([ \j -gt 0 ] && echo [\j])\[\$txtrst\]$\e[m "
+}
